# Generated by Django 6.0.4 on 2026-04-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="professores/"),
        ),
    ]
