# Generated by Django 6.0.4 on 2026-04-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_professor_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="numero",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
