# Generated by Django 6.0.4 on 2026-04-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0003_alter_aluno_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
