from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('licenciaturas/', views.licenciaturas_view, name='licenciaturas'),
    path('ucs/', views.ucs_view, name='ucs'),
    path('docentes/', views.docentes_view, name='docentes'),
    path('tfcs/', views.tfcs_view, name='tfcs'),
    path('projetos/', views.projetos_view, name='projetos'),
    path('projetos/novo/', views.projeto_criar, name='projeto_criar'),
    path('projetos/<int:pk>/editar/', views.projeto_editar, name='projeto_editar'),
    path('projetos/<int:pk>/apagar/', views.projeto_apagar, name='projeto_apagar'),
    path('tecnologias/', views.tecnologias_view, name='tecnologias'),
    path('tecnologias/nova/', views.tecnologia_criar, name='tecnologia_criar'),
    path('tecnologias/<int:pk>/editar/', views.tecnologia_editar, name='tecnologia_editar'),
    path('tecnologias/<int:pk>/apagar/', views.tecnologia_apagar, name='tecnologia_apagar'),
    path('competencias/', views.competencias_view, name='competencias'),
    path('competencias/nova/', views.competencia_criar, name='competencia_criar'),
    path('competencias/<int:pk>/editar/', views.competencia_editar, name='competencia_editar'),
    path('competencias/<int:pk>/apagar/', views.competencia_apagar, name='competencia_apagar'),
    path('formacoes/', views.formacoes_view, name='formacoes'),
    path('formacoes/nova/', views.formacao_criar, name='formacao_criar'),
    path('formacoes/<int:pk>/editar/', views.formacao_editar, name='formacao_editar'),
    path('formacoes/<int:pk>/apagar/', views.formacao_apagar, name='formacao_apagar'),
    path('experiencias/', views.experiencias_view, name='experiencias'),
    path('sobre/', views.sobre_view, name='sobre'),
    path('makingof/', views.makingof_view, name='makingof'),
    path('makingof/<int:pk>/', views.makingof_view, name='makingof_detalhe'),
]