# Generated by Django 6.0.4 on 2026-04-10 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url_pagina_lusofona', models.URLField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/')),
            ],
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=20)),
                ('instituicao', models.CharField(default='Universidade Lusófona', max_length=150)),
                ('ano_inicio', models.IntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('ano', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('url_repositorio', models.URLField(blank=True)),
                ('url_demo', models.URLField(blank=True)),
                ('conceitos_aplicados', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework'), ('bd', 'Base de Dados'), ('ferramenta', 'Ferramenta'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('url_oficial', models.URLField(blank=True)),
                ('nivel', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermédio'), (3, 'Avançado')], default=1)),
                ('destaque', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('tecnica', 'Técnica'), ('soft', 'Soft Skill'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('projetos', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.projeto')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.tecnologia')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia'),
        ),
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('entidade_relacionada', models.CharField(choices=[('licenciatura', 'Licenciatura'), ('uc', 'Unidade Curricular'), ('projeto', 'Projeto'), ('tecnologia', 'Tecnologia'), ('competencia', 'Competência'), ('formacao', 'Formação'), ('tfc', 'TFC'), ('experiencia', 'Experiência Profissional'), ('geral', 'Geral')], max_length=30)),
                ('descricao', models.TextField()),
                ('decisoes_tomadas', models.TextField(blank=True)),
                ('erros_encontrados', models.TextField(blank=True)),
                ('correcoes', models.TextField(blank=True)),
                ('uso_ia', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='makingof/')),
                ('data', models.DateField(auto_now_add=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.projeto')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='makingofs', to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('instituicao', models.CharField(max_length=150)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='formacoes/')),
                ('url', models.URLField(blank=True)),
                ('competencias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.competencia')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('competencias', models.ManyToManyField(blank=True, related_name='experiencias', to='portfolio.competencia')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='experiencias', to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('orientador', models.CharField(blank=True, max_length=150)),
                ('ano', models.IntegerField()),
                ('resumo', models.TextField(blank=True)),
                ('url_repositorio', models.URLField(blank=True)),
                ('interesse', models.IntegerField(default=1, help_text='1 a 5')),
                ('competencias', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.competencia')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ucs/')),
                ('docentes', models.ManyToManyField(blank=True, related_name='ucs', to='portfolio.docente')),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucs', to='portfolio.licenciatura')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='portfolio.unidadecurricular'),
        ),
    ]
