# Generated by Django 6.0.4 on 2026-04-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfc',
            old_name='resumo',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='licenciatura',
            name='sigla',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='conceitos_aplicados',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='url_demo',
        ),
        migrations.RemoveField(
            model_name='tecnologia',
            name='destaque',
        ),
        migrations.RemoveField(
            model_name='tecnologia',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='tecnologia',
            name='url_oficial',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='interesse',
        ),
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='sigla',
        ),
    ]
