# Generated by Django 6.0.4 on 2026-04-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_resumo_tfc_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='destaque',
            field=models.TextField(blank=True, help_text='O que de mais relevante aprendeste'),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tecnologias/'),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='url_tecnologia',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='interesse',
            field=models.IntegerField(default=1, help_text='1 a 5 — nível de interesse'),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ucs/'),
        ),
    ]
