# Generated by Django 6.0.4 on 2026-04-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_tecnologia_destaque_tecnologia_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='url_pagina_lusofona',
        ),
    ]
