# Generated by Django 6.0.4 on 2026-04-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_docente_url_pagina_lusofona'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='url_pagina_lusofona',
            field=models.URLField(blank=True),
        ),
    ]
