# Generated by Django 6.0.4 on 2026-04-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_docente_url_pagina_lusofona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnologia',
            name='descricao',
        ),
    ]
