# Generated by Django 6.0.4 on 2026-04-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_tecnologia_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='competencias',
        ),
        migrations.AddField(
            model_name='competencia',
            name='experiencias',
            field=models.ManyToManyField(blank=True, related_name='competencias_adquiridas', to='portfolio.experienciaprofissional'),
        ),
    ]
