# Generated by Django 6.0.4 on 2026-04-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_experienciaprofissional_competencias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienciaprofissional',
            old_name='descricao',
            new_name='descricaoEmpresarial',
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='Funcao',
            field=models.TextField(blank=True),
        ),
    ]
