# Generated by Django 6.0.4 on 2026-04-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_descricao_experienciaprofissional_descricaoempresarial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienciaprofissional',
            old_name='Funcao',
            new_name='descricao_Cargo',
        ),
        migrations.RenameField(
            model_name='experienciaprofissional',
            old_name='descricaoEmpresarial',
            new_name='descricao_Empresa',
        ),
    ]
