# Generated by Django 6.0.4 on 2026-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_rename_funcao_experienciaprofissional_descricao_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makingof',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='makingof/'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='makingof/'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='justificacao_modelacao',
            field=models.TextField(blank=True),
        ),
    ]
