# Generated by Django 6.0.4 on 2026-04-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_makingof_foto2_makingof_foto3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makingof',
            name='data',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='tecnologias',
        ),
    ]
