# Generated by Django 6.0.4 on 2026-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_makingof_data_remove_makingof_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makingof',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='makingof/'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='foto5',
            field=models.ImageField(blank=True, null=True, upload_to='makingof/'),
        ),
        migrations.AlterField(
            model_name='makingof',
            name='entidade_relacionada',
            field=models.CharField(choices=[('licenciatura', 'Licenciatura'), ('uc', 'Unidade Curricular'), ('projeto', 'Projeto'), ('tecnologia', 'Tecnologia'), ('competencia', 'Competência'), ('formacao', 'Formação'), ('tfc', 'TFC'), ('experiencia', 'Experiência Profissional'), ('MakingOf', 'MakingOf')], max_length=30),
        ),
    ]
