# Generated by Django 6.0.4 on 2026-04-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_aluno_professor_curso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="alunos",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="professor",
        ),
        migrations.DeleteModel(
            name="Aluno",
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
        migrations.DeleteModel(
            name="Professor",
        ),
    ]
