# Generated by Django 6.0.4 on 2026-04-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_remove_curso_alunos_remove_curso_professor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("bd", "Base de Dados"),
                            ("storage", "Storage"),
                            ("outros", "Outros"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecnologias",
                to="portfolio.tipotecnologia",
            ),
        ),
    ]
