# Generated by Django 6.0.4 on 2026-04-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_tipotecnologia_tecnologia_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="entidade_relacionada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("licenciatura", "Licenciatura"),
                    ("uc", "Unidade Curricular"),
                    ("projeto", "Projeto"),
                    ("tecnologia", "Tecnologia"),
                    ("competencia", "Competência"),
                    ("formacao", "Formação"),
                    ("tfc", "TFC"),
                    ("experiencia", "Experiência Profissional"),
                    ("MakingOf", "MakingOf"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
