# Generated by Django 6.0.4 on 2026-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_alter_makingof_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
