# Generated by Django 6.0.4 on 2026-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_alter_tfc_autor_alter_tfc_orientador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
