# Generated by Django 6.0.4 on 2026-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_alter_tfc_autor_alter_tfc_orientador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.TextField(blank=True),
        ),
    ]
